# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: FloatFerry
email: ym3410@gmail.com
timezone: null
description: > # this means to ignore newlines until "baseurl:"
  데모 사이트
baseurl: # the subpath of your site, e.g. /blog
url: https://floatferry.github.io # the base hostname & protocol for your site
twitter_username: 
github_username:  FloatFerry

permalink: /:year-:month-:day-:title/

# Build settings
markdown: kramdown

plugins_dir:
- jekyll-relative-links

exclude:
- Gemfile
- .sass-cache
